### ISSUE TITLE
Linux: Blank white screen after update

### ISSUE THREAD

**Issue by k1l1** [buchen/portfolio#1720] opened 2020-09-02 10:47 UTC
**Describe the bug**
After the last update Portfolio Performance only shows a blank white screen. No open File, no error messages.

**Comment by BastiS** [comment] 2020-09-02 15:39
Same for me on Windows 10.
After the last upgrade it just shows a blank window without any menu items and no error message.
I even rebooted my computer, but still no luck. Let me know if I can help debugging the issue.
![image](https://user-images.githubusercontent.com/1009665/92004926-1e969c00-ed43-11ea-8f0e-ffa3755b7f82.png)

**Comment by BastiS** [comment] 2020-09-02 15:43
Looks like a duplicate of #1712 
I'll reinstall it unless providing any logs would help finding the root cause of this.

**Closed** 2020-10-07 12:41 UTC
Labels: bug
