### ISSUE TITLE
Non-destructive Sort

### ISSUE THREAD

**Issue by flywire** [buchen/portfolio#2370] opened 2021-08-06 11:06 UTC
**Is your feature request related to a problem? Please describe.**
Sorting is a really useful way of ordering data to analyse it, eg an alphabetically ordered list is quicker to search than a randomly ordered one. Sorting on multiple attributes is even more useful.

**Describe the solution you'd like**
A non-destructive sort allows table columns to be sorted by attributes sequentially. eg sort by security name then number of shares would give a list ordered by number of shares then name where the number of shares are the same. This is especially useful where there are a small number categories, eg closed trades, a binary taxonomy.

**Describe alternatives you've considered**
Export to csv and load into a spreadsheet.

**Additional context**
![image](https://user-images.githubusercontent.com/11288701/128499916-db99b261-c02e-4a1f-a64f-c632564b69f1.png)
Sort by name.

![image](https://user-images.githubusercontent.com/11288701/128499986-4219093b-bc22-4713-a87e-c7a8a5132783.png)
Sort by Shares - Note names with 100 shares are no longer sorted ascending.

---

btw, Performance Calculation sort just sorts by Label, sorting by Value just sorts by Label.

**Comment by chirlu** [comment] 2021-08-06 17:27
Duplicate of #1440.

**Closed** 2021-08-07 00:17 UTC
