### ISSUE TITLE
Number format without thousands separator in CSV import

### ISSUE THREAD

**Issue by seg-on** [buchen/portfolio#3156] opened 2023-01-31 10:09 UTC
Is it possible to add a number format for the number of stocks without a thousands separator and with a comma to separate tenths? For example 123456,123
Here use in CSV import:
![image](https://user-images.githubusercontent.com/19683952/215725019-ba3a83a9-49e4-44e7-a3d5-f518fde5252f.png)

**Comment by flywire** [comment] 2023-02-03 21:44
Duplicate of #2945

**Closed** 2023-03-05 19:57 UTC
