### ISSUE TITLE
Allow filters to be changed

### ISSUE THREAD

**Issue by funnym0nk3y** [buchen/portfolio#2491] opened 2021-11-01 12:30 UTC
**Is your feature request related to a problem? Please describe.**
According to this forum thread [wrong link] some people wish for an option to change filters. Me too. 

**Describe alternatives you've considered**
Editing the xml file is a very technical way and shouldn't be the default way of doing this.

**Comment by OnkelDok** [comment] 2021-11-02 18:48
I guess your link ist not the correct one.
Do you mean this PP forum thread: https://forum.portfolio-performance.info/t/bestehende-filter-erweitern/7355

Is this a duplicate of #1375?

**Comment by funnym0nk3y** [comment] 2021-11-02 19:33
This is awkward 🙈

**Closed** 2021-11-02 19:33 UTC
