### ISSUE TITLE
Reporting currency drop-down doesn’t scroll

### ISSUE THREAD

**Issue by chirlu** [buchen/portfolio#1920] opened 2020-12-30 21:44 UTC
When the drop-down menu at the top right of the “Statement of assets” view is too tall to fit on the screen (which it usually is), it is impossible to scroll down to those entries that are off-screen. (It **is** possible to select off-screen entries via the keyboard, by pressing the cursor-down key repeatedly, then the enter key; but I can’t see what I am selecting that way until after the fact.)

I’m on Linux.

Steps to reproduce: 1. Go to the “Statement of assets” view. 2. Click on the label for the current reporting currency (e.g. “EUR”) or the arrow next to it. 3. (The menu appears.) 4. Try to select a currency that is way down the list.

Related observations:
* The same menu is also available as a submenu from the main menu bar (File › Currency). In that incarnation, however, small arrows appear at the top and/or bottom when approaching the limits of the screen, and the visible part of the list scrolls up and down as expected, allowing any currency to be selected easily.
* A similar drop-down exists in the dialogue for adding/editing a security. When activated by mouse, scrolling works here; when the same drop-down is activated by keyboard (putting focus there via the tab key, then pressing the space key), there is no scrolling.
* The currency drop-down in the “Accounts” view (which only displays the three-letter codes for the currencies) scrolls normally.

**Comment by chrisaut** [comment] 2020-12-31 10:35
I think this is just a dupe of #1876

**Comment by chirlu** [comment] 2020-12-31 14:32
No, an implementation of #1876 might well fix this issue (or not, if the new submenu is unscrollable as well), but this is plainly a bug.

Perhaps you don’t see the issue? It might well be platform-specific. I can’t test it on Windows or MacOS, though.

**Comment by buchen** [comment] 2021-01-03 10:29
Hi @chirlu,

with https://github.com/buchen/portfolio/issues/1876#issuecomment-753596281 I have shortened the menus. Is it better now?

Unfortunately, I have no control of the menus itself let alone whether scroll bars appear or not. On macOS it works fine. The menus are created by SWT.

**Comment by chirlu** [comment] 2021-01-03 10:54
Yes, the sub-menus are short enough each so that they fit without scrolling.

As I said, *some* menus do scroll correctly. No idea what the reason for the difference is.

**Closed** 2021-01-06 21:09 UTC
Labels: bug
