### ISSUE TITLE
Make currency section editable

### ISSUE THREAD

**Issue by curbaczek** [buchen/portfolio#2382] opened 2021-08-09 11:55 UTC
**Is your feature request related to a problem? Please describe.**
As discussed in the PP forum ([here](https://forum.portfolio-performance.info/t/einnahmen-aus-lending-staking-von-kryptowaehrungen/11498/11) and [here](https://forum.portfolio-performance.info/t/tausch-von-cryptowahrungen-z-b-ethereum-mit-bitcoin/5763)) some users have issues with the fact that it is necessary to book earnings in crypto currencies by adding e.g. dividend (USD/EUR) and buy (USD/EUR -> BTC) orders of the given token. Especially within the lending and staking area that means additional manual work (e.g. buying ETH with BTC means different price calculations) and changed statistics (e.g. buying price, dividend yield, ...).

**Describe the solution you'd like**
It would be great if the currency section would be editable so users can add crypto currencies as currencies. With that it should be possible to use these currencies to document lending/staking earnings in that given currency as dividends/interests rather than simulate a dividend and a "virtual" buy.

**Describe alternatives you've considered**
Alternatively a stock gift option could be a solution. Currently crypto currencies are defined as stocks within PP. If I'm correct there are currently no option no get stocks for free and add it to the system. So this feature seems to be also useful for stocks.

**Comment by chirlu** [comment] 2021-08-09 17:35
Duplicate of #1633.

**Closed** 2022-03-08 14:56 UTC
